### ISSUE TITLE
Add Upload and Edit Options for New Posts in Profile

### ISSUE THREAD

**Issue by akramcodez** [akramcodez/Animal-Profile-Page-Search#3]
Enable users to upload media (images, videos, or files) when creating new posts directly from their profile page. Additionally, users should have the option to edit these posts and update the uploaded content later. This feature will provide more flexibility and improve the overall user experience in managing profile posts.

**Comment by Arshmac** [comment]
assign me

**Comment by akramcodez** [comment]
[Arshmac](https://github.com/Arshmac) now you are assigned :-)
