### ISSUE TITLE
Create Home Page for Animal Profile Instagram Clone

### ISSUE THREAD

**Issue by akramcodez** [akramcodez/Animal-Profile-Page-Search#7]
We need a clean and engaging home page for our Instagram-inspired clone, focused on animal profile pages. This page should introduce users to the platform and invite them to explore different animal profiles.

**Comment by Abhijit8951** [comment]
Assign me!

**Comment by akramcodez** [comment]
> Assign me!

@Abhijit8951 now you are assigned :-)
